/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AccNumber": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EmailFrom": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MjmlAppId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MjmlSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SparkPostApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}